service:
  name: giphy-proxy

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2
  environment:
    API_KEY: ${env:API_KEY}

custom:
  customDomain:
    domainName: ${env:DOMAIN_NAME}
    certificateName: ${env:CERTIFICATE_NAME}
    createRoute53Record: true
    endpointType: "regional"

functions:
  fetchRandom50:
    handler: handler.fetchRandom50
    events:
      - http:
          method: get
          path: random50
  listAll:
    handler: handler.listAll
    events:
      - http:
          method: get
          path: all
          cors: true
  search:
    handler: handler.search
    events:
      - http:
          method: get
          path: search
          cors: true
  getItem:
    handler: handler.getItem
    events:
      - http:
          path: /{id}
          method: get
          request:
            parameters:
              paths:
                id: true
          cors: true
